

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GEOMATIC_SUITE(object):
    def setupUi(self, GEOMATIC_SUITE):
        GEOMATIC_SUITE.setObjectName("GEOMATIC_SUITE")
        GEOMATIC_SUITE.resize(819, 285)
        GEOMATIC_SUITE.setStyleSheet("background-color: rgb(170, 167, 165);")
        self.centralwidget = QtWidgets.QWidget(GEOMATIC_SUITE)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 28))
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(0, 46))
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 42))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.horizontalFrame)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(3, "")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        GEOMATIC_SUITE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GEOMATIC_SUITE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName("menubar")
        GEOMATIC_SUITE.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GEOMATIC_SUITE)
        self.statusbar.setObjectName("statusbar")
        GEOMATIC_SUITE.setStatusBar(self.statusbar)

        self.retranslateUi(GEOMATIC_SUITE)
        QtCore.QMetaObject.connectSlotsByName(GEOMATIC_SUITE)

    def retranslateUi(self, GEOMATIC_SUITE):
        _translate = QtCore.QCoreApplication.translate
        GEOMATIC_SUITE.setWindowTitle(_translate("GEOMATIC_SUITE", "GEOMATIC SUITE"))
        self.label.setText(_translate("GEOMATIC_SUITE", "GEOMATIC TASK AUTOMATION SUITE"))
        self.label_2.setText(_translate("GEOMATIC_SUITE", "TYPE OF TASK"))
        self.comboBox.setItemText(0, _translate("GEOMATIC_SUITE", "TACHEOMETRIC DETAILING/LEVELLING/TRAVERSING"))
        self.comboBox.setItemText(1, _translate("GEOMATIC_SUITE", "SPIRIT_LEVELLING"))
        self.comboBox.setItemText(2, _translate("GEOMATIC_SUITE", "DATUM TRANSFORMATION"))
        self.pushButton.setText(_translate("GEOMATIC_SUITE", "ENTER"))
        self.label_3.setText(_translate("GEOMATIC_SUITE", "THIS APP WAS DEVELOPED BY MR  MARTIN  ABORGEH, AN INTERMEDIATE PROGRAMMER AND SOFTWARE DEVELEPER PURPOSELY TO AUTOMATE GEOMATIC TASKS"))
